"""Auto-generated by ground_truth.py — do not edit by hand."""
from __future__ import annotations
import hashlib
import math
from datetime import datetime, timedelta, timezone
from zoneinfo import ZoneInfo

OSLO = ZoneInfo("Europe/Oslo")
UTC = timezone.utc
ALARM_COMPANY = 4.0
BEARING_TEMP_ALARM = 85.0
DE_TARGET_0922 = 3.80
TS_START = datetime(2026, 7, 25, 0, 0, tzinfo=UTC)
SERIES_IDS = [
    "pal_50-VT-101A-DE","pal_50-VT-101A-NDE","pal_50-TT-101A-DE","pal_50-PT-101A-DIS",
    "pal_50-VT-101B-DE","pal_50-VT-101B-NDE","pal_50-TT-101B-DE","pal_50-PT-101B-DIS",
    "pal_50-TT-105-OS","pal_50-LT-105",
]

def _noise(series_id: str, ts: datetime, amplitude: float) -> float:
    key = f"{series_id}|{int(ts.timestamp())}".encode()
    h = hashlib.sha256(key).digest()
    u = int.from_bytes(h[:8], "big") / (2**64 - 1)
    return (u * 2.0 - 1.0) * amplitude

def _is_monday_test_run(ts: datetime) -> bool:
    local = ts.astimezone(OSLO)
    if local.weekday() != 0:
        return False
    minutes = local.hour * 60 + local.minute
    return 10 * 60 <= minutes < 12 * 60

def _smoothstep(x: float) -> float:
    x = max(0.0, min(1.0, x))
    return x * x * (3 - 2 * x)

def value_at(series_id: str, ts: datetime) -> float:
    t0 = datetime(2026, 9, 1, 0, 0, tzinfo=UTC)
    t_peak = datetime(2026, 9, 22, 12, 0, tzinfo=UTC)
    days_from_start = (ts - t0).total_seconds() / 86400.0
    days_to_peak = (t_peak - t0).total_seconds() / 86400.0
    if series_id == "pal_50-VT-101A-DE":
        base = 2.1
        if ts < t0: v = base
        elif ts <= t_peak:
            u = _smoothstep(days_from_start / days_to_peak)
            frac = 0.35 * u + 0.65 * u * u
            v = base + (DE_TARGET_0922 - base) * frac
        else:
            days_after = (ts - t_peak).total_seconds() / 86400.0
            v = DE_TARGET_0922 + 0.035 * days_after
        return max(0.0, v + _noise(series_id, ts, 0.05))
    if series_id == "pal_50-VT-101A-NDE":
        base, peak = 1.6, 2.4
        if ts < t0: v = base
        elif ts <= t_peak:
            u = _smoothstep(days_from_start / days_to_peak)
            v = base + (peak - base) * (0.35 * u + 0.65 * u * u)
        else:
            days_after = (ts - t_peak).total_seconds() / 86400.0
            v = peak + 0.02 * days_after
        return max(0.0, v + _noise(series_id, ts, 0.05))
    if series_id == "pal_50-TT-101A-DE":
        base, peak = 68.0, 79.0
        if ts < t0: v = base
        elif ts <= t_peak:
            u = _smoothstep(days_from_start / days_to_peak)
            v = base + (peak - base) * u
        else:
            days_after = (ts - t_peak).total_seconds() / 86400.0
            v = peak + 0.15 * days_after
        return min(BEARING_TEMP_ALARM - 0.5, v + _noise(series_id, ts, 0.5))
    if series_id == "pal_50-PT-101A-DIS":
        return 6.2 + _noise(series_id, ts, 0.1)
    if series_id in ("pal_50-VT-101B-DE","pal_50-VT-101B-NDE","pal_50-TT-101B-DE","pal_50-PT-101B-DIS"):
        running = _is_monday_test_run(ts)
        if series_id == "pal_50-VT-101B-DE":
            return (2.3 if running else 0.1) + _noise(series_id, ts, 0.05 if running else 0.02)
        if series_id == "pal_50-VT-101B-NDE":
            return (1.7 if running else 0.1) + _noise(series_id, ts, 0.05 if running else 0.02)
        if series_id == "pal_50-PT-101B-DIS":
            return (6.2 if running else 0.0) + _noise(series_id, ts, 0.05 if running else 0.01)
        if not running:
            return 25.0 + _noise(series_id, ts, 0.3)
        local = ts.astimezone(OSLO)
        into = (local.hour * 60 + local.minute - 600) / 120.0
        warm = 1.0 - math.exp(-3.0 * into)
        target = 70.0 if local.month >= 9 else 66.0
        return 25.0 + (target - 25.0) * warm + _noise(series_id, ts, 0.4)
    if series_id == "pal_50-TT-105-OS":
        return 45.0 + _noise(series_id, ts, 0.5)
    if series_id == "pal_50-LT-105":
        t_rise = datetime(2026, 8, 15, 0, 0, tzinfo=UTC)
        t_drop = datetime(2026, 8, 20, 10, 0, tzinfo=UTC)
        t_end = datetime(2026, 9, 22, 12, 0, tzinfo=UTC)
        if ts < t_rise: v = 62.0
        elif ts < t_drop:
            u = (ts - t_rise).total_seconds() / (t_drop - t_rise).total_seconds()
            v = 62.0 + 6.0 * u
        elif ts < t_drop + timedelta(hours=1): v = 60.0
        else:
            u = min(1.0, (ts - t_drop).total_seconds() / (t_end - t_drop).total_seconds())
            v = 60.0 + 6.0 * u
        return v + _noise(series_id, ts, 0.3)
    raise KeyError(series_id)
